{% set name = "protoletariat" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 93ad2de075ea5fa38a066fb1ffee75ecebe61e7cc5626dfb2b11a9d5cb854d27

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - protol = protoletariat.__main__:main

requirements:
  host:
    - python >=3.7
    - pip
    - poetry
  run:
    - python >=3.7
    - astunparse <2,>=1.6.3
    - click <9,>=8
    - protobuf <5,>=3.19.1

test:
  requires:
    - pytest
    - mypy-protobuf
    - grpcio
    - grpc-cpp
  imports:
    - protoletariat
    - protoletariat.tests
  commands:
    - protol
    - protol --help
    - pytest --pyargs protoletariat -k 'not test_version'

about:
  home: https://github.com/cpcloud/protoletariat
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Protocol buffers for the rest of us
  description: |
    protoletariat is a tool for fixing the imports in stock protoc or buf
    generated Python code
  dev_url: https://github.com/cpcloud/protoletariat

extra:
  recipe-maintainers:
    - cpcloud
