{% set name = "protoletariat" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 77080a5b67c1027ad9620b989fd438ba35aeebf0a16ed5c2388ebc43f015ac22

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - protol = protoletariat.__main__:main

requirements:
  host:
    - python >=3.7
    - pip
    - poetry
  run:
    - python >=3.7
    - astunparse <2.0.0,>=1.6.3
    - click <9.0.0,>=8.0.1
    - protobuf <4.0.0,>=3.19.1

test:
  requires:
    - pytest
    - mypy-protobuf
    - grpcio
  imports:
    - protoletariat
    - protoletariat.tests
  commands:
    - protol
    - protol --help
    - pytest --pyargs protoletariat

about:
  home: https://github.com/cpcloud/protoletariat
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Protocol buffers for the rest of us
  description: |
    protoletariat is a tool for fixing the imports in stock protoc or buf
    generated Python code
  dev_url: https://github.com/cpcloud/protoletariat

extra:
  recipe-maintainers:
    - cpcloud
