{% set name = "protoletariat" %}
{% set version = "3.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bcdeaea70b0b517f91f3e636101f55be2e7590730d8126632ebb9919665d8d99

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - protol = protoletariat.__main__:main

requirements:
  host:
    - python >=3.7
    - pip
    - poetry
  run:
    - python >=3.7
    - astunparse <2,>=1.6.3
    - click <9,>=8
    - protobuf <6,>=3.19.1
    # - grpcio-tools <2,>=1.42.0
    # - grpcio-tools <2,>=1.42.0
    # - grpcio-tools <2,>=1.42.0

test:
  requires:
    - pytest
    - mypy-protobuf
    - grpcio
    - grpc-cpp
  imports:
    - protoletariat
    - protoletariat.tests
  commands:
    - protol
    - protol --help
    - pytest --pyargs protoletariat -k 'not test_version'

about:
  home: https://github.com/cpcloud/protoletariat
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Protocol buffers for the rest of us
  description: |
    protoletariat is a tool for fixing the imports in stock protoc or buf
    generated Python code
  dev_url: https://github.com/cpcloud/protoletariat

extra:
  recipe-maintainers:
    - cpcloud
