{% set name = "protoletariat" %}
{% set version = "0.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 43b30d3484294ff0f46d978cd4ab9f28219d6f5ae8371e6ded06dbe2f92526af

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - protol = protoletariat.__main__:main

requirements:
  host:
    - python >=3.7
    - pip
    - poetry
  run:
    - python >=3.7
    - click >=8.0.1,<9
    - protobuf >=3.19.1,<4
    - typed-ast >=1.4.0,<2
    - astunparse >=1.6.3,<2

test:
  requires:
    - pytest
  imports:
    - protoletariat
    - protoletariat.tests
  commands:
    - protol
    - protol --help
    - pytest --pyargs protoletariat

about:
  home: https://github.com/cpcloud/protoletariat
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Protocol buffers for the rest of us
  description: |
    protoletariat is a tool for fixing the imports in stock protoc or buf
    generated Python code
  dev_url: https://github.com/cpcloud/protoletariat

extra:
  recipe-maintainers:
    - cpcloud
